services:

  mysql:
    image: mysql:8.0
    container_name: employee-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employee123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .

    container_name: employee-app

    ports:
      - "5000:5000"

    depends_on:
      - mysql

volumes:
  mysql_data:
